export const Scene_Menu = 'Menu'
export const Scene_GameClassic = 'GameClassic'
export const Scene_GameMarathon = 'GameMarathon'
export const Scene_Settings = 'Settings'
export const Scene_GameResults = 'GameResults'
